import { ROLES } from "../constants/roles.js";

export const NAV_ITEMS = {
  [ROLES.SUPER_ADMIN]: [
    { label: "Dashboard", path: "/dashboard", icon: "home" },
    { label: "Courses", path: "/dashboard/courses", icon: "book" },
    { label: "Attendance", path: "/dashboard/attendance", icon: "check" },
    { label: "Finance", path: "/dashboard/finance", icon: "money" },
    { label: "Campaigns", path: "/dashboard/finance/campaigns", icon: "target" },
    { label: "Donations", path: "/dashboard/finance/donations", icon: "gift" },
    { label: "Expenses", path: "/dashboard/finance/expenses", icon: "receipt" },
    { label: "Budgets", path: "/dashboard/finance/budgets", icon: "wallet" },
    { label: "Reports", path: "/dashboard/finance/reports", icon: "chart" },
    { label: "Users", path: "/dashboard/users", icon: "users" },
    { label: "Profiles", path: "/dashboard/profiles", icon: "profile" },
    { label: "System", path: "/dashboard/system", icon: "settings" },
  ],
  [ROLES.ADMIN]: [
    { label: "Dashboard", path: "/dashboard", icon: "home" },
    { label: "Courses", path: "/dashboard/courses", icon: "book" },
    { label: "Attendance", path: "/dashboard/attendance", icon: "check" },
    { label: "Finance", path: "/dashboard/finance", icon: "money" },
    { label: "Campaigns", path: "/dashboard/finance/campaigns", icon: "target" },
    { label: "Donations", path: "/dashboard/finance/donations", icon: "gift" },
    { label: "Expenses", path: "/dashboard/finance/expenses", icon: "receipt" },
    { label: "Budgets", path: "/dashboard/finance/budgets", icon: "wallet" },
    { label: "Reports", path: "/dashboard/finance/reports", icon: "chart" },
    { label: "Teachers", path: "/dashboard/teachers", icon: "users" },
    { label: "Students", path: "/dashboard/students", icon: "students" },
    { label: "Profiles", path: "/dashboard/profiles", icon: "profile" },
  ],
  [ROLES.TEACHER]: [
    { label: "Dashboard", path: "/dashboard", icon: "home" },
    { label: "Courses", path: "/dashboard/courses", icon: "book" },
    { label: "Attendance", path: "/dashboard/attendance", icon: "check" },
    { label: "Campaigns", path: "/dashboard/finance/campaigns", icon: "target" },
    { label: "My Donations", path: "/dashboard/my-donations", icon: "gift" },
    { label: "Students", path: "/dashboard/students", icon: "students" },
    { label: "Profiles", path: "/dashboard/profiles", icon: "profile" },
  ],
  [ROLES.STUDENT]: [
    { label: "Dashboard", path: "/dashboard", icon: "home" },
    { label: "My Courses", path: "/dashboard/courses", icon: "book" },
    { label: "My Attendance", path: "/dashboard/my-attendance", icon: "check" },
    { label: "Certificates", path: "/dashboard/certificates", icon: "award" },
    { label: "My Donations", path: "/dashboard/my-donations", icon: "gift" },
    { label: "Progress", path: "/dashboard/progress", icon: "chart" },
    { label: "My Profile", path: "/dashboard/profile", icon: "profile" },
  ],
  [ROLES.PARENT]: [
    { label: "Dashboard", path: "/dashboard", icon: "home" },
    { label: "Courses", path: "/dashboard/courses", icon: "book" },
    { label: "Children", path: "/dashboard/children", icon: "users" },
    {
      label: "Attendance",
      path: "/dashboard/parent-attendance",
      icon: "check",
    },
    { label: "My Donations", path: "/dashboard/my-donations", icon: "gift" },
    { label: "Progress", path: "/dashboard/progress-parent", icon: "chart" },
    { label: "My Profile", path: "/dashboard/profile", icon: "profile" },
  ],
};
