import { ROLES } from "../constants/roles.js";
import { BarChart3, Bell, Megaphone, CalendarDays, Building2, DoorOpen, FileText } from "lucide-react";

export const NAV_ITEMS = {
  [ROLES.SUPER_ADMIN]: [
    { label: "Dashboard", path: "/dashboard", icon: "home" },
    { label: "Notifications", path: "/dashboard/notifications", icon: Bell },
    { label: "Announcements", path: "/dashboard/announcements", icon: Megaphone },
    { label: "Courses", path: "/dashboard/courses", icon: "book" },
    { label: "Attendance", path: "/dashboard/attendance", icon: "check" },
    { label: "Finance", path: "/dashboard/finance", icon: "money" },
    {
      label: "Campaigns",
      path: "/dashboard/finance/campaigns",
      icon: "target",
    },
    { label: "Donations", path: "/dashboard/finance/donations", icon: "gift" },
    { label: "Expenses", path: "/dashboard/finance/expenses", icon: "receipt" },
    { label: "Budgets", path: "/dashboard/finance/budgets", icon: "wallet" },
    { label: "Reports", path: "/dashboard/finance/reports", icon: "chart" },
    { label: "Users", path: "/dashboard/users", icon: "users" },
    { label: "Profiles", path: "/dashboard/profiles", icon: "profile" },
    { label: "System", path: "/dashboard/system", icon: "settings" },
    { label: "Audit Logs", path: "/dashboard/audit-logs", icon: "file-text" },
    { label: "Activity", path: "/dashboard/activity", icon: "activity" },
    { label: "Login History", path: "/dashboard/login-history", icon: "log-in" },
    { label: "Cert. Download Requests", path: "/dashboard/certificates/download-requests", icon: "award" },
    { label: "Calendar", path: "/dashboard/calendar", icon: CalendarDays },
    { label: "Events", path: "/dashboard/events", icon: DoorOpen },
    { label: "Manage Events", path: "/dashboard/admin/events", icon: DoorOpen },
    { label: "Rooms", path: "/dashboard/rooms", icon: Building2 },
    { label: "Manage Rooms", path: "/dashboard/admin/rooms", icon: Building2 },
    { label: "Manage Bookings", path: "/dashboard/admin/bookings", icon: CalendarDays },
    { label: "Analytics", path: "/dashboard/analytics", icon: BarChart3 },
    { label: "Reports", path: "/dashboard/reports", icon: FileText },
  ],
  [ROLES.ADMIN]: [
    { label: "Dashboard", path: "/dashboard", icon: "home" },
    { label: "Notifications", path: "/dashboard/notifications", icon: Bell },
    { label: "Announcements", path: "/dashboard/announcements", icon: Megaphone },
    { label: "Courses", path: "/dashboard/courses", icon: "book" },
    { label: "Attendance", path: "/dashboard/attendance", icon: "check" },
    { label: "Finance", path: "/dashboard/finance", icon: "money" },
    {
      label: "Campaigns",
      path: "/dashboard/finance/campaigns",
      icon: "target",
    },
    { label: "Donations", path: "/dashboard/finance/donations", icon: "gift" },
    { label: "Expenses", path: "/dashboard/finance/expenses", icon: "receipt" },
    { label: "Budgets", path: "/dashboard/finance/budgets", icon: "wallet" },
    { label: "Reports", path: "/dashboard/finance/reports", icon: "chart" },
    { label: "Calendar", path: "/dashboard/calendar", icon: CalendarDays },
    { label: "Events", path: "/dashboard/events", icon: DoorOpen },
    { label: "Manage Events", path: "/dashboard/admin/events", icon: DoorOpen },
    { label: "Rooms", path: "/dashboard/rooms", icon: Building2 },
    { label: "Manage Rooms", path: "/dashboard/admin/rooms", icon: Building2 },
    { label: "Manage Bookings", path: "/dashboard/admin/bookings", icon: CalendarDays },
    { label: "Teachers", path: "/dashboard/teachers", icon: "users" },
    { label: "Students", path: "/dashboard/students", icon: "students" },
    { label: "Profiles", path: "/dashboard/profiles", icon: "profile" },
    {
      label: "Analytics",
      path: "/dashboard/analytics",
      icon: BarChart3,
    },
    { label: "Reports", path: "/dashboard/reports", icon: FileText },
    { label: "Audit Logs", path: "/dashboard/audit-logs", icon: "file-text" },
    { label: "Activity", path: "/dashboard/activity", icon: "activity" },
    { label: "Cert. Download Requests", path: "/dashboard/certificates/download-requests", icon: "award" },
  ],
  [ROLES.TEACHER]: [
    { label: "Dashboard", path: "/dashboard", icon: "home" },
    { label: "Notifications", path: "/dashboard/notifications", icon: Bell },
    { label: "Announcements", path: "/dashboard/announcements", icon: Megaphone },
    { label: "Courses", path: "/dashboard/courses", icon: "book" },
    { label: "Attendance", path: "/dashboard/attendance", icon: "check" },
    {
      label: "Campaigns",
      path: "/dashboard/finance/campaigns",
      icon: "target",
    },
    { label: "Calendar", path: "/dashboard/calendar", icon: CalendarDays },
    { label: "Events", path: "/dashboard/events", icon: DoorOpen },
    { label: "Rooms", path: "/dashboard/rooms", icon: Building2 },
    { label: "My Donations", path: "/dashboard/my-donations", icon: "gift" },
    { label: "Students", path: "/dashboard/students", icon: "students" },
    { label: "Profiles", path: "/dashboard/profiles", icon: "profile" },
    {
      label: "Analytics",
      path: "/dashboard/analytics",
      icon: BarChart3,
    },
  ],
  [ROLES.STUDENT]: [
    { label: "Dashboard", path: "/dashboard", icon: "home" },
    { label: "Notifications", path: "/dashboard/notifications", icon: Bell },
    { label: "Announcements", path: "/dashboard/announcements", icon: Megaphone },
    { label: "My Courses", path: "/dashboard/courses", icon: "book" },
    { label: "My Attendance", path: "/dashboard/my-attendance", icon: "check" },
    { label: "Certificates", path: "/dashboard/certificates", icon: "award" },
    { label: "Calendar", path: "/dashboard/calendar", icon: CalendarDays },
    { label: "Events", path: "/dashboard/events", icon: DoorOpen },
    { label: "My Donations", path: "/dashboard/my-donations", icon: "gift" },
    { label: "Progress", path: "/dashboard/progress", icon: "chart" },
    { label: "My Profile", path: "/dashboard/profile", icon: "profile" },
  ],
  [ROLES.PARENT]: [
    { label: "Dashboard", path: "/dashboard", icon: "home" },
    { label: "Notifications", path: "/dashboard/notifications", icon: Bell },
    { label: "Announcements", path: "/dashboard/announcements", icon: Megaphone },
    { label: "Courses", path: "/dashboard/courses", icon: "book" },
    { label: "Children", path: "/dashboard/children", icon: "users" },
    {
      label: "Attendance",
      path: "/dashboard/parent-attendance",
      icon: "check",
    },
    { label: "Calendar", path: "/dashboard/calendar", icon: CalendarDays },
    { label: "Events", path: "/dashboard/events", icon: DoorOpen },
    { label: "My Donations", path: "/dashboard/my-donations", icon: "gift" },
    { label: "Progress", path: "/dashboard/progress-parent", icon: "chart" },
    { label: "My Profile", path: "/dashboard/profile", icon: "profile" },
  ],
};
