export const AUDIT_MODULES = {
  AUTH: "Authentication",
  USER: "User",
  COURSE: "Course",
  LESSON: "Lesson",
  ENROLLMENT: "Enrollment",
  ATTENDANCE: "Attendance",
  CERTIFICATE: "Certificate",
  DONATION: "Donation",
  EXPENSE: "Expense",
  CAMPAIGN: "Campaign",
  FINANCE: "Finance",
  PROFILE: "Profile",
  NOTIFICATION: "Notification",
  ANNOUNCEMENT: "Announcement",
  REPORT: "Report",
  SYSTEM: "System",
  AUDIT: "Audit",
};

export const AUDIT_ACTIONS = {
  LOGIN: "Login",
  LOGOUT: "Logout",
  CREATE: "Create",
  UPDATE: "Update",
  DELETE: "Delete",
  APPROVE: "Approve",
  REJECT: "Reject",
  EXPORT: "Export",
  PRINT: "Print",
  UPLOAD: "Upload",
  DOWNLOAD: "Download",
  VIEW: "View",
  REGISTER: "Register",
  ENROLL: "Enroll",
  COMPLETE: "Complete",
  ISSUE: "Issue",
  SEND: "Send",
  PUBLISH: "Publish",
  SYNC: "Sync",
  ARCHIVE: "Archive",
  RESTORE: "Restore",
};

export const ACTIVITY_TYPES = {
  USER_LOGIN: "user_login",
  USER_LOGOUT: "user_logout",
  PROFILE_UPDATE: "profile_update",
  PASSWORD_CHANGE: "password_change",
  COURSE_CREATED: "course_created",
  COURSE_UPDATED: "course_updated",
  COURSE_DELETED: "course_deleted",
  LESSON_CREATED: "lesson_created",
  ENROLLMENT: "enrollment",
  ATTENDANCE: "attendance",
  CERTIFICATE_ISSUED: "certificate_issued",
  DONATION_CREATED: "donation_created",
  EXPENSE_CREATED: "expense_created",
  CAMPAIGN_CREATED: "campaign_created",
  ANNOUNCEMENT_PUBLISHED: "announcement_published",
  NOTIFICATION_SENT: "notification_sent",
  VOLUNTEER_ASSIGNED: "volunteer_assigned",
  PARENT_LINKED: "parent_linked",
};
